tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/bundle"

## 1. Chat / Call
cask "slack"
cask "discord" 
cask "telegram" 
cask "whatsapp" 
# "zoom" 

## 2. Media
cask "spotify" 
cask "vlc" 
# stremio
# preview 


## 3. Office
cask "google-drive" 
cask "adobe-acrobat-reader" 
# textedit 
# cask "microsoft-excel"
# cask "microsoft-powerpoint"
# cask "microsoft-word"


## 4. Productivity
cask "marta"
cask "brave-browser"
cask "iterm2"
cask "visual-studio-code"
# cask "postman"
cask "docker" 
cask "arduino-ide"
# openlens
# safari

## 5. Settings
# app store 
# system preferences 
# activity monitor 
# mission control 
# find my 

## 6. Tools
cask "simplenote" 
cask "authy" 
cask "send-to-kindle"
cask "rectangle" 
cask "the-unarchiver" 
cask "raycast"
cask "macmediakeyforwarder"
cask "clocker"
cask "aldente"
mas "Horo", id: 1437226581
# mas "Pocket", id: 568494494
# photo boot 
# calculator 
# tableplus
# wireshark
# amphetamine
# ledger
# loom
# deepl
# protonvpn
# duplicate-file-finder

## Development tools
brew "pre-commit"
# brew "composer"
# brew "ruby"
# brew "python"
brew "awscli"
brew "node"
brew "antigen"
brew "zsh"

## System tools
brew "git"
brew "curl"
brew "nmap"
brew "wget"
brew "grep"
brew "tree"
brew "watch"
brew "telnet"
brew "gcc"
brew "openssl"
brew "jq"
brew "gnu-tar"
brew "gnu-sed"
brew "gnu-time"
brew "gnu-which"
brew "gnutls"
brew "gnupg"
brew "mas"

## Terraform tools
brew "tfenv"
brew "tflint"
brew "tfsec"
# tap "coretech/terrafile"
# brew "terrafile"
brew "terraform-docs"
# tap "gofireflyio/aiac"
# brew "aiac"
# brew "terrascan"